---
title: "More than noise?: Signal variability measures, single trial analysis"
author: "José C. García Alanis"
date:  "`r Sys.Date()`"
output:
  html_document:
    theme: lumen
    highlight: pygments
    css: "styler.css"
---

Created with `r R.version.string`

```{r, setup, include = FALSE}
knitr::opts_chunk$set(class.source = "customCode",
                      class.output = "customOutput",
                      class.message = "customWarning")
if (interactive()) {
  path <- dirname(rstudioapi::getSourceEditorContext()$path)
} else {
  path <- normalizePath('./')
}
setwd(path)
source('utils.R')
```

```{r session-preferences, include = FALSE}
load.package(
        c('foreach',
          'rjson', 'dplyr', 'tidyr', 'stringr',
          'afex', 'optimx',
          'performance', 'emmeans', 'effectsize',
          'ggplot2')
)

# adjust the plotting theme
theme_set(
        theme_linedraw() +
                theme(panel.grid = element_blank(),
                      strip.background = element_rect(fill = "grey92",
                                                      color = "grey92"),
                      strip.text = element_text(color = "black", size = 10)
                )
)

# scale function
scale2 <- function(x, na.rm = TRUE) (x - mean(x, na.rm = na.rm)) / sd(x, na.rm)

# parallel settings
n.cores <- 4
my.cluster <- parallel::makeCluster(
        n.cores,
        type = "PSOCK"
)
# print(my.cluster)

# register it to be used by %dopar%
doParallel::registerDoParallel(cl = my.cluster)

#c heck if it is registered (optional)
# foreach::getDoParRegistered()

# function for combining output of foreach
comb <- function(List1, List2) {
  output_a <- c(List1[[1]], List2[[1]])
  output_b <- c(List1[[2]], List2[[2]])
  return(list(contrasts = output_a, effects = output_b))
}
```

```{r import-data}
# get paths to Odd/Even task PSD
paths <- fromJSON(file = "paths.json")
fpath_sigle_trial_var <- paste(
        paths$bids,
        'derivatives',
        'analysis_dataframes',
        'single_trial_variability.rds',
        sep = '/'
)

signal_variability_st <- readRDS(fpath_sigle_trial_var)
```

```{r}
test <- signal_variability_st %>%
        filter(task == 'Odd/Even', sensor == 0, accuracy == 'Correct') %>%
        select(`1f_exponent`, stimulus, window, condition) %>%
        mutate(tw = paste(stringr::str_to_title(window),
                              stringr::str_to_title(stimulus))) %>%
        mutate(tw = factor(tw, levels = c('Pre Cue', 'Post Cue', 'Post Target')))

ggplot(test, aes(x = tw, y = `1f_exponent`, color = condition)) +
        stat_summary(fun = mean, geom = 'point') +
        stat_summary(fun = mean, geom = 'line', aes(group = condition))
```


```{r}
# place holder for results
sensor_effects <- data.frame()
sensor_contrasts <- data.frame()

measures <- c("permutation_entropy", "weighted_permutation_entropy",
              "multiscale_entropy", "ms_1", "ms_2", "ms_3", "ms_4", "ms_slope",
              "activity", "mobility", "complexity",
              "1f_offset", "1f_exponent",
              "spectral_entropy")

# loop accross tasks
for (task_i in unique(signal_variability_st$task)) {

  # run model for each sensor
  for (sensor_n in unique(signal_variability_st$sensor)[1:2]) {

    # get sensor data
    sensor <- signal_variability_st %>%
            ungroup() %>%
            filter(sensor == sensor_n) %>%
            pivot_longer(cols = permutation_entropy:spectral_entropy,
                         names_to = "var_meas", values_to = "var") %>%
            filter(!is.na(var)) %>%
            mutate(tw = paste(stringr::str_to_title(window),
                              stringr::str_to_title(stimulus))) %>%
            mutate(tw = factor(tw, levels = c('Pre Cue', 'Post Cue', 'Post Target')),
                   task = factor(task, levels = c('Odd/Even', 'Number/Letter')),
                   condition = factor(condition, labels = c('Repeat', 'Switch'))
            )

    # and euch measure
    sensor_results <- foreach(
            meas = measures,
            .combine = 'comb',
            .init = list(list(), list())
    ) %dopar% {

      # packages for analysis
      require(dplyr)
      require(afex)
      require(emmeans)

      # # * for debbuging purposes *
      # print(paste0('Running model for sensor: ', sensor_n, '. Measure: ', meas))

      # get measure of interest
      dat <- sensor %>%
              filter(var_meas == meas,
                     task == task_i)

      # fit LMM
      var_mxd <- mixed(
              var ~ tw * condition + (tw * condition || subject),
              dat,
              method = 'S',
              check_contrasts = TRUE,
              all_fit = TRUE,
              expand_re = TRUE,
              control = lmerControl(optCtrl = list(maxfun = 1e6))
      )

      o2 <- effectsize::F_to_omega2(f = var_mxd$anova_table$F,
                                    df = var_mxd$anova_table$`num Df`,
                                    df_error = var_mxd$anova_table$`den Df`,
                                    ci = 0.99)
      o2 <- data.frame(o2)

      # model performance
      df_model_fit <- performance::model_performance(var_mxd$full_model) %>%
              data.frame() %>%
              mutate(predictor = row.names(var_mxd$anova_table),
                     F = var_mxd$anova_table$F,
                     p = var_mxd$anova_table$`Pr(>F)`,
                     o_sq = o2$Omega2_partial,
                     o_sq_ci = o2$CI,
                     o_sq_CI_low = o2$CI_low,
                     o_sq_CI_high = o2$CI_high,
                     optimiser = attr(var_mxd$full_model, 'optinfo')$optimizer,
                     sensor = sensor_n + 1,
                     measure = meas,
                     task = task_i)

      # compute contrasts
      var_eff <- emmeans(
              var_mxd$full_model, ~ tw,
              type = 'response',
              lmer.df = "satterthwaite",
              lmerTest.limit = nrow(dat),
              level = 0.99
      )
      contr_var_eff <- contrast(var_eff, method = 'pairwise', adjust = 'holm')
      contr_var_eff <- data.frame(contr_var_eff)

      # compute effect sizes
      contr_d <- effectsize::t_to_d(
              t = contr_var_eff$t.ratio,
              df = contr_var_eff$df,
              paired = TRUE,
              ci = 0.99
      )

      # make effect sizes table
      contr_d <- contr_d %>%
              data.frame() %>%
              mutate(contrast = contr_var_eff$contrast,
                     sensor = sensor_n + 1,
                     measure = meas,
                     task = task_i)

      # output of foreach
      list(contrasts = list(contr_d), effects = list(df_model_fit))

    }

    # save model fits
    fits <- sensor_results[2] %>%
            bind_rows()
    sensor_effects <- rbind(sensor_effects, fits)

    # save effect sizes
    eff_sizes <- sensor_results[1] %>%
            bind_rows()
    sensor_contrasts <- rbind(sensor_contrasts, eff_sizes)

  }

}
```
