name: mne
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - pip
  - numpy==1.24.4
  - scipy==1.11.2
  - matplotlib==3.7.1
  - ipykernel==6.25.1
  - ipython==8.14.0
  - pooch==1.7.0
  - jinja2==3.1.2
  - numba==0.57.1
  - pandas==2.0.3
  - mne-base==1.5.0
  - pip:
    - ipympl
    - mne-bids==0.13
    - pyprep==0.4.2
    - mne-icalabel==0.4
    - click==8.1.7
    - fooof==1.0.0
    - neurodsp==2.2.1
    - antropy==0.1.6
    - neurokit2==0.2.5
